name: mdt
version: '0.1'
summary: A tool for flashing your devices 
description: |
  A simple and feature full batch tool to handle installing/replacing
  Operating Systems (Ubuntu Phone / Ubuntu Touch, Android, LineageOS,
  Maru OS, Sailfish OS and Phoenix OS) on your mobile devices.

grade: devel
confinement: strict

parts:
  mdt:
    plugin: qmake
    qt-version: qt5
    project-files: [Magic-UI.pro]
    source: https://github.com/MariusQuabeck/magic-device-tool/tree/gui/Magic-UI
    install: |
     install -d $SNAPCRAFT_PART_INSTALL/opt/mdt
     install Magic-UI $SNAPCRAFT_PART_INSTALL/opt/mdt/Magic-UI
#     build-packages:
#         - build-essential
#         - qttools5-dev-tools
#         - qtbase5-dev
#         - qtdeclarative5-dev
    stage-packages:
         - android-tools-adb
         - android-tools-fastboot
         - wget
         - usbutils
         - ubuntu-device-flash
    after: [desktop-qt5]

apps:
  mdt-launch:
    command: desktop-launch "$SNAP/opt/mdt/Magic-UI"
#   desktop: /path-to-folder../snap/gui/mdt-launch.desktop
    plugs: [unity7, network, raw-usb]
